version: 2
jobs:
  build:

    docker:
      - image: circleci/buildpack-deps:bionic

    steps:

      - checkout

      - setup_remote_docker

      - run:
          name: "Setup Environment Variables"
          command: |
            echo 'export QGIS_REPOSITORY="${QGIS_REPOSITORY:-https://github.com/qgis/QGIS.git}"' >> $BASH_ENV
            echo 'export QGIS_BRANCH="${QGIS_BRANCH:-master}"' >> $BASH_ENV
            echo 'export QGIS_TAG="${QGIS_TAG:-master}"' >> $BASH_ENV
            echo 'export CPU_CORES="${CPU_CORES:-2}"' >> $BASH_ENV

      - run:
          command: |
          echo "Docker TAG: ${QGIS_TAG}"
          
      - run:
          name: "Build the Docker image"
          command: >
            docker build  -t elpaso/qgis-testing-environment:${QGIS_TAG}
            --build-arg QGIS_REPOSITORY=$QGIS_REPOSITORY
            --build-arg QGIS_BRANCH=$QGIS_BRANCH
            --build-arg CPU_CORES=$CPU_CORES
            .

      - run:
          name: "Tag Docker image"
          command: |
            docker tag elpaso/qgis-testing-environment:${QGIS_TAG} elpaso/qgis-testing-environment:latest

      - run:
          name: "Deploy Docker image"
          command: |
            if [ "${QGIS_TAG}" == "master" ]; then
              docker push elpaso/qgis-testing-environment:latest
            fi
            docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
            docker push elpaso/qgis-testing-environment:${QGIS_TAG}
